# Generated by Django 4.0.4 on 2022-05-10 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snacks', '0002_coolsnack'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpicySnack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('spicy', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='coolSnack',
        ),
    ]
